local tbl = 
{
	filename = "Mash-5.41 Diadem Artisanal MIN",
	glist = 
	{
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32044,
			job = 16,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Prismstone",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 902673,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32043,
			job = 16,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Silex",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1013364,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32042,
			job = 16,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Ice Stalagmite",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1059499,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32041,
			job = 16,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Spring Water",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1071355,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32040,
			job = 16,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Cloudstone",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1080529,
		},
	},
	orders = 
	{
	},
}



return tbl