local tbl = 
{
	filename = "Mash-5.41 Diadem Artisanal MIN-BTN",
	glist = 
	{
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32044,
			job = 16,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Prismstone",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 991198,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32043,
			job = 16,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Silex",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 904495,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32042,
			job = 16,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Ice Stalagmite",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 927420,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32041,
			job = 16,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Spring Water",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1009335,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32040,
			job = 16,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Cloudstone",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 944194,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32039,
			job = 17,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Barbgrass",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 949769,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32038,
			job = 17,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Cocoon",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1196558,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32037,
			job = 17,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Caiman",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1033708,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32036,
			job = 17,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Raspberry",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 935725,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32035,
			job = 17,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Log",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 901400,
		},
	},
	orders = 
	{
	},
}



return tbl