local tbl = 
{
	filename = "Mash-5.3 Diadem BTN",
	glist = 
	{
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31310,
			job = 17,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Vine",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1155285,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31309,
			job = 17,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Rice",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1084576,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31308,
			job = 17,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Cotton Boll",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 977126,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31307,
			job = 17,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Amber",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1169915,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31306,
			job = 17,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Log",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1094968,
		},
	},
	orders = 
	{
	},
}



return tbl