local tbl = 
{
	filename = "Mash-Diadem MIN-BTN",
	glist = 
	{
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31311,
			job = 16,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Cloudstone",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1081298,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31312,
			job = 16,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Basilisk Egg",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1123973,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31313,
			job = 16,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Alumen",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1173495,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31314,
			job = 16,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Clay",
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1086306,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			gearset = 0,
			hidden = false,
			hold = false,
			id = 31315,
			job = 16,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Granite",
			notinlistcaseid = 0,
			okgp = 0,
			p_detail = "[MIN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1031803,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31306,
			job = 17,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Log",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1189435,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31307,
			job = 17,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Amber",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1046297,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31308,
			job = 17,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Cotton Boll",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 900000,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31309,
			job = 17,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Rice",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1075475,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 31310,
			job = 17,
			mapid = 901,
			name = "Grade 3 Artisanal Skybuilders' Vine",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "community\\Nagishiro-Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1161007,
		},
	},
	orders = 
	{
	},
}



return tbl