local tbl = 
{
	filename = "Mash-5.41 Diadem Artisanal BTN",
	glist = 
	{
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32039,
			job = 17,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Barbgrass",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1082150,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32038,
			job = 17,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Cocoon",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 949870,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32037,
			job = 17,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Caiman",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1098914,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32036,
			job = 17,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Raspberry",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1035237,
		},
		
		{
			HQamount = 0,
			amount = 99999,
			collect = false,
			cordial = true,
			hold = false,
			id = 32035,
			job = 17,
			mapid = 901,
			name = "Grade 4 Artisanal Skybuilders' Log",
			okgp = 0,
			p_detail = "[BTN] Diadem",
			point = 9999,
			reserve = false,
			skillname = "Diadem_K2.lua",
			skillnum = 6,
			skip = false,
			tasktype = "gather",
			timerValue = 1005637,
		},
	},
	orders = 
	{
	},
}



return tbl